name: CICD

on:
  workflow_dispatch:
  schedule:
    - cron: "0 03 * * *"        
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to docker hub using secrets in GitHub.
      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build for testing
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          load: true
          tags: tang:test

      - name: Test the image
        run: |
          docker run -d --name tang-test -p 8080:8080 tang:test
          sleep 5
          curl -f http://localhost:8080/adv
          docker stop tang-test
          docker rm tang-test

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: kvalitetsit/tang:latest,kvalitetsit/tang:${{ github.sha }}
          sbom: true
          provenance: true

      - name: Is Tag Build
        id: tag
        if:  ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Build and test helm chart
        run: ./build/build-helm.sh tang ${{ steps.tag.outputs.VERSION }} ${{ steps.tag.outputs.VERSION }}

      - name: Push tagged helm chart to repo
        if: ${{ steps.tag.conclusion != 'skipped' }}
        run: ./build/push-repo.sh ${{ secrets.KIT_GITHUB_ACCESS }}